-- Clear existing data
TRUNCATE ratings, nominations, ceremonies, players RESTART IDENTITY CASCADE;

-- Insert all players (ON CONFLICT to avoid duplicates)
INSERT INTO players (name, nationality, club, position, photo_url) VALUES
-- Modern era players (1998-2025) with photos
('Lionel Messi', 'Argentina', 'Inter Miami', 'FWD', 'https://upload.wikimedia.org/wikipedia/commons/thumb/b/b4/Lionel-Messi-Argentina-2022-FIFA-World-Cup_%28cropped%29.jpg/400px-Lionel-Messi-Argentina-2022-FIFA-World-Cup_%28cropped%29.jpg'),
('Cristiano Ronaldo', 'Portugal', 'Al Nassr', 'FWD', 'https://upload.wikimedia.org/wikipedia/commons/thumb/8/8c/Cristiano_Ronaldo_2018.jpg/400px-Cristiano_Ronaldo_2018.jpg'),
('Ousmane Dembélé', 'France', 'PSG', 'FWD', 'https://upload.wikimedia.org/wikipedia/commons/thumb/8/8e/Ousmane_Demb%C3%A9l%C3%A9_2019.jpg/400px-Ousmane_Demb%C3%A9l%C3%A9_2019.jpg'),
('Lamine Yamal', 'Spain', 'Barcelona', 'FWD', 'https://upload.wikimedia.org/wikipedia/commons/thumb/4/44/Lamine_Yamal_2024.jpg/400px-Lamine_Yamal_2024.jpg'),
('Vitinha', 'Portugal', 'PSG', 'MID', 'https://upload.wikimedia.org/wikipedia/commons/thumb/2/25/Vitinha_%282023%29.jpg/400px-Vitinha_%282023%29.jpg'),
('Mohamed Salah', 'Egypt', 'Liverpool', 'FWD', 'https://upload.wikimedia.org/wikipedia/commons/thumb/c/c1/Mohamed_Salah_2018.jpg/400px-Mohamed_Salah_2018.jpg'),
('Raphinha', 'Brazil', 'Barcelona', 'FWD', 'https://upload.wikimedia.org/wikipedia/commons/thumb/7/76/Raphinha_2023.jpg/400px-Raphinha_2023.jpg'),
('Achraf Hakimi', 'Morocco', 'PSG', 'DEF', 'https://upload.wikimedia.org/wikipedia/commons/thumb/8/80/Achraf_Hakimi_2022.jpg/400px-Achraf_Hakimi_2022.jpg'),
('Kylian Mbappé', 'France', 'Real Madrid', 'FWD', 'https://upload.wikimedia.org/wikipedia/commons/thumb/5/57/2019-07-17_SG_Dynamo_Dresden_v_Paris_Saint-Germain_FC_by_Sandro_Halank%E2%80%93195_%28cropped%29.jpg/400px-2019-07-17_SG_Dynamo_Dresden_v_Paris_Saint-Germain_FC_by_Sandro_Halank%E2%80%93195_%28cropped%29.jpg'),
('Cole Palmer', 'England', 'Chelsea', 'MID', 'https://upload.wikimedia.org/wikipedia/commons/thumb/3/3e/Cole_Palmer_2024.jpg/400px-Cole_Palmer_2024.jpg'),
('Gianluigi Donnarumma', 'Italy', 'PSG', 'GK', 'https://upload.wikimedia.org/wikipedia/commons/thumb/f/f9/Donnarumma_2020.jpg/400px-Donnarumma_2020.jpg'),
('Nuno Mendes', 'Portugal', 'PSG', 'DEF', 'https://upload.wikimedia.org/wikipedia/commons/thumb/2/25/Nuno_Mendes_2022.jpg/400px-Nuno_Mendes_2022.jpg'),
('Rodri', 'Spain', 'Manchester City', 'MID', 'https://upload.wikimedia.org/wikipedia/commons/thumb/b/b9/Rodri_2022.jpg/400px-Rodri_2022.jpg'),
('Vinícius Júnior', 'Brazil', 'Real Madrid', 'FWD', 'https://upload.wikimedia.org/wikipedia/commons/thumb/f/f8/Vinicius_Junior_2022.jpg/400px-Vinicius_Junior_2022.jpg'),
('Jude Bellingham', 'England', 'Real Madrid', 'MID', 'https://upload.wikimedia.org/wikipedia/commons/thumb/9/9b/Jude_Bellingham_2023.jpg/400px-Jude_Bellingham_2023.jpg'),
('Erling Haaland', 'Norway', 'Manchester City', 'FWD', 'https://upload.wikimedia.org/wikipedia/commons/thumb/8/87/Erling_Haaland_2023.jpg/400px-Erling_Haaland_2023.jpg'),
('Karim Benzema', 'France', 'Al Ittihad', 'FWD', 'https://upload.wikimedia.org/wikipedia/commons/thumb/0/0a/Karim_Benzema_2019.jpg/400px-Karim_Benzema_2019.jpg'),
('Sadio Mané', 'Senegal', 'Al Nassr', 'FWD', 'https://upload.wikimedia.org/wikipedia/commons/thumb/a/a6/Sadio_Man%C3%A9_2019.jpg/400px-Sadio_Man%C3%A9_2019.jpg'),
('Kevin De Bruyne', 'Belgium', 'Manchester City', 'MID', 'https://upload.wikimedia.org/wikipedia/commons/thumb/e/e2/Kevin_De_Bruyne_2021.jpg/400px-Kevin_De_Bruyne_2021.jpg'),
('Robert Lewandowski', 'Poland', 'Barcelona', 'FWD', 'https://upload.wikimedia.org/wikipedia/commons/thumb/0/03/Robert_Lewandowski%2C_Poland_national_football_team_%2801%29.jpg/400px-Robert_Lewandowski%2C_Poland_national_football_team_%2801%29.jpg'),
('Jorginho', 'Italy', 'Arsenal', 'MID', 'https://upload.wikimedia.org/wikipedia/commons/thumb/b/b3/Jorginho_2018.jpg/400px-Jorginho_2018.jpg'),
('Virgil van Dijk', 'Netherlands', 'Liverpool', 'DEF', 'https://upload.wikimedia.org/wikipedia/commons/thumb/a/ad/Virgil_van_Dijk_2019.jpg/400px-Virgil_van_Dijk_2019.jpg'),
('Luka Modrić', 'Croatia', 'Real Madrid', 'MID', 'https://upload.wikimedia.org/wikipedia/commons/thumb/8/84/Luka_Modri%C4%87_in_2018.jpg/400px-Luka_Modri%C4%87_in_2018.jpg'),
('Antoine Griezmann', 'France', 'Atletico Madrid', 'FWD', 'https://upload.wikimedia.org/wikipedia/commons/thumb/4/4c/Antoine_Griezmann_2018.jpg/400px-Antoine_Griezmann_2018.jpg'),
('Neymar', 'Brazil', 'Al Hilal', 'FWD', 'https://upload.wikimedia.org/wikipedia/commons/thumb/b/bc/Brasili_vs_Cro%C3%A0cia_%28173%29_cropped.jpg/400px-Brasili_vs_Cro%C3%A0cia_%28173%29_cropped.jpg'),
('Manuel Neuer', 'Germany', 'Bayern Munich', 'GK', 'https://upload.wikimedia.org/wikipedia/commons/thumb/b/b5/Manuel_Neuer_2018.jpg/400px-Manuel_Neuer_2018.jpg'),
('Franck Ribéry', 'France', 'Retired', 'FWD', 'https://upload.wikimedia.org/wikipedia/commons/thumb/6/6e/Franck_Rib%C3%A9ry_2013.jpg/400px-Franck_Rib%C3%A9ry_2013.jpg'),
('Andrés Iniesta', 'Spain', 'Retired', 'MID', 'https://upload.wikimedia.org/wikipedia/commons/thumb/7/72/Andres_iniesta_2012.jpg/400px-Andres_iniesta_2012.jpg'),
('Xavi Hernández', 'Spain', 'Retired', 'MID', 'https://upload.wikimedia.org/wikipedia/commons/thumb/a/a5/Xavi_2014.jpg/400px-Xavi_2014.jpg'),
('Fernando Torres', 'Spain', 'Retired', 'FWD', 'https://upload.wikimedia.org/wikipedia/commons/thumb/f/f7/Fernando_Torres_2012.jpg/400px-Fernando_Torres_2012.jpg'),
('Kaká', 'Brazil', 'Retired', 'MID', 'https://upload.wikimedia.org/wikipedia/commons/thumb/b/b8/Kaka_2013.jpg/400px-Kaka_2013.jpg'),
('Ronaldinho', 'Brazil', 'Retired', 'FWD', 'https://upload.wikimedia.org/wikipedia/commons/thumb/e/ec/Ronaldinho_-_Manchester_City_vs_Barcelona_%28cropped%29.jpg/400px-Ronaldinho_-_Manchester_City_vs_Barcelona_%28cropped%29.jpg'),
('Ronaldo Nazário', 'Brazil', 'Retired', 'FWD', 'https://upload.wikimedia.org/wikipedia/commons/thumb/3/34/Ronaldo_real_madrid.jpg/400px-Ronaldo_real_madrid.jpg'),
('Zinedine Zidane', 'France', 'Retired', 'MID', 'https://upload.wikimedia.org/wikipedia/commons/thumb/f/f3/Zinedine_Zidane_by_Tasnim_03.jpg/400px-Zinedine_Zidane_by_Tasnim_03.jpg'),
('Rivaldo', 'Brazil', 'Retired', 'FWD', 'https://upload.wikimedia.org/wikipedia/commons/thumb/b/b2/Rivaldo2005.jpg/400px-Rivaldo2005.jpg'),
('Luis Figo', 'Portugal', 'Retired', 'MID', 'https://upload.wikimedia.org/wikipedia/commons/thumb/d/dd/Luis_Figo_2019.jpg/400px-Luis_Figo_2019.jpg'),
('Michael Owen', 'England', 'Retired', 'FWD', 'https://upload.wikimedia.org/wikipedia/commons/thumb/d/d5/Michael_Owen_2007.jpg/400px-Michael_Owen_2007.jpg'),
('Pavel Nedvěd', 'Czech Republic', 'Retired', 'MID', 'https://upload.wikimedia.org/wikipedia/commons/thumb/e/e2/Pavel_Nedved.jpg/400px-Pavel_Nedved.jpg'),
('Andriy Shevchenko', 'Ukraine', 'Retired', 'FWD', 'https://upload.wikimedia.org/wikipedia/commons/thumb/6/6c/Andriy_Shevchenko.jpg/400px-Andriy_Shevchenko.jpg'),
('Deco', 'Portugal', 'Retired', 'MID', 'https://upload.wikimedia.org/wikipedia/commons/thumb/6/65/Deco_2008.jpg/400px-Deco_2008.jpg'),
('Frank Lampard', 'England', 'Retired', 'MID', 'https://upload.wikimedia.org/wikipedia/commons/thumb/d/d6/Frank_Lampard_2014.jpg/400px-Frank_Lampard_2014.jpg'),
('Steven Gerrard', 'England', 'Retired', 'MID', 'https://upload.wikimedia.org/wikipedia/commons/thumb/4/47/Steven_Gerrard_2014.jpg/400px-Steven_Gerrard_2014.jpg'),
('Fabio Cannavaro', 'Italy', 'Retired', 'DEF', 'https://upload.wikimedia.org/wikipedia/commons/thumb/e/e3/Fabio_Cannavaro_2006.jpg/400px-Fabio_Cannavaro_2006.jpg'),
('Gianluigi Buffon', 'Italy', 'Retired', 'GK', 'https://upload.wikimedia.org/wikipedia/commons/thumb/2/2d/Gigi_Buffon_2015.jpg/400px-Gigi_Buffon_2015.jpg'),
('Thierry Henry', 'France', 'Retired', 'FWD', 'https://upload.wikimedia.org/wikipedia/commons/thumb/6/6f/Thierry_Henry_2019.jpg/400px-Thierry_Henry_2019.jpg'),
('Raúl González', 'Spain', 'Retired', 'FWD', 'https://upload.wikimedia.org/wikipedia/commons/thumb/8/8e/Ra%C3%BAl_Gonz%C3%A1lez_2011.jpg/400px-Ra%C3%BAl_Gonz%C3%A1lez_2011.jpg'),
('Oliver Kahn', 'Germany', 'Retired', 'GK', 'https://upload.wikimedia.org/wikipedia/commons/thumb/0/05/Oliver_Kahn.jpg/400px-Oliver_Kahn.jpg'),
('Roberto Carlos', 'Brazil', 'Retired', 'DEF', 'https://upload.wikimedia.org/wikipedia/commons/thumb/a/ab/Roberto_Carlos_2019.jpg/400px-Roberto_Carlos_2019.jpg'),
('David Beckham', 'England', 'Retired', 'MID', 'https://upload.wikimedia.org/wikipedia/commons/thumb/9/98/David_Beckham_-_styled_%28cropped%29.jpg/400px-David_Beckham_-_styled_%28cropped%29.jpg'),
('Paolo Maldini', 'Italy', 'Retired', 'DEF', 'https://upload.wikimedia.org/wikipedia/commons/thumb/4/4e/Paolo_Maldini.jpg/400px-Paolo_Maldini.jpg'),
('Hristo Stoichkov', 'Bulgaria', 'Retired', 'FWD', 'https://upload.wikimedia.org/wikipedia/commons/thumb/6/6f/Hristo_Stoichkov_2018.jpg/400px-Hristo_Stoichkov_2018.jpg'),
('Roberto Baggio', 'Italy', 'Retired', 'FWD', 'https://upload.wikimedia.org/wikipedia/commons/thumb/0/04/Roberto_Baggio_-_1994.jpg/400px-Roberto_Baggio_-_1994.jpg'),
('George Weah', 'Liberia', 'Retired', 'FWD', 'https://upload.wikimedia.org/wikipedia/commons/thumb/8/87/George_Weah_2019.jpg/400px-George_Weah_2019.jpg'),
-- Older era players (pre-1998) without photos
('Stanley Matthews', 'England', 'Retired', 'FWD', NULL),
('Alfredo Di Stéfano', 'Spain', 'Retired', 'FWD', NULL),
('Raymond Kopa', 'France', 'Retired', 'FWD', NULL),
('Billy Wright', 'England', 'Retired', 'DEF', NULL),
('Helmut Rahn', 'Germany', 'Retired', 'FWD', NULL),
('Just Fontaine', 'France', 'Retired', 'FWD', NULL),
('John Charles', 'Wales', 'Retired', 'FWD', NULL),
('Luis Suárez Miramontes', 'Spain', 'Retired', 'MID', NULL),
('Ferenc Puskás', 'Hungary', 'Retired', 'FWD', NULL),
('Uwe Seeler', 'Germany', 'Retired', 'FWD', NULL),
('Omar Sívori', 'Argentina', 'Retired', 'FWD', NULL),
('Johnny Haynes', 'England', 'Retired', 'MID', NULL),
('Josef Masopust', 'Czechoslovakia', 'Retired', 'MID', NULL),
('Eusébio', 'Portugal', 'Retired', 'FWD', NULL),
('Karl-Heinz Schnellinger', 'Germany', 'Retired', 'DEF', NULL),
('Lev Yashin', 'Soviet Union', 'Retired', 'GK', NULL),
('Gianni Rivera', 'Italy', 'Retired', 'MID', NULL),
('Jimmy Greaves', 'England', 'Retired', 'FWD', NULL),
('Denis Law', 'Scotland', 'Retired', 'FWD', NULL),
('Amancio Amaro', 'Spain', 'Retired', 'FWD', NULL),
('Eusébio da Silva', 'Portugal', 'Retired', 'FWD', NULL),
('Giacinto Facchetti', 'Italy', 'Retired', 'DEF', NULL),
('Bobby Charlton', 'England', 'Retired', 'MID', NULL),
('Franz Beckenbauer', 'Germany', 'Retired', 'DEF', NULL),
('Flórian Albert', 'Hungary', 'Retired', 'FWD', NULL),
('Jimmy Johnstone', 'Scotland', 'Retired', 'FWD', NULL),
('George Best', 'Northern Ireland', 'Retired', 'FWD', NULL),
('Dragan Džajić', 'Yugoslavia', 'Retired', 'FWD', NULL),
('Luigi Riva', 'Italy', 'Retired', 'FWD', NULL),
('Gerd Müller', 'Germany', 'Retired', 'FWD', NULL),
('Bobby Moore', 'England', 'Retired', 'DEF', NULL),
('Johan Cruyff', 'Netherlands', 'Retired', 'FWD', NULL),
('Sandro Mazzola', 'Italy', 'Retired', 'FWD', NULL),
('Günter Netzer', 'Germany', 'Retired', 'MID', NULL),
('Dino Zoff', 'Italy', 'Retired', 'GK', NULL),
('Kazimierz Deyna', 'Poland', 'Retired', 'MID', NULL),
('Oleg Blokhin', 'Soviet Union', 'Retired', 'FWD', NULL),
('Rob Rensenbrink', 'Netherlands', 'Retired', 'FWD', NULL),
('Ivo Viktor', 'Czechoslovakia', 'Retired', 'GK', NULL),
('Allan Simonsen', 'Denmark', 'Retired', 'FWD', NULL),
('Kevin Keegan', 'England', 'Retired', 'FWD', NULL),
('Michel Platini', 'France', 'Retired', 'MID', NULL),
('Hans Krankl', 'Austria', 'Retired', 'FWD', NULL),
('Ruud Krol', 'Netherlands', 'Retired', 'DEF', NULL),
('Karl-Heinz Rummenigge', 'Germany', 'Retired', 'FWD', NULL),
('Bernd Schuster', 'Germany', 'Retired', 'MID', NULL),
('Paul Breitner', 'Germany', 'Retired', 'MID', NULL),
('Paolo Rossi', 'Italy', 'Retired', 'FWD', NULL),
('Alain Giresse', 'France', 'Retired', 'MID', NULL),
('Zbigniew Boniek', 'Poland', 'Retired', 'MID', NULL),
('Kenny Dalglish', 'Scotland', 'Retired', 'FWD', NULL),
('Jean Tigana', 'France', 'Retired', 'MID', NULL),
('Preben Elkjær', 'Denmark', 'Retired', 'FWD', NULL),
('Igor Belanov', 'Soviet Union', 'Retired', 'FWD', NULL),
('Gary Lineker', 'England', 'Retired', 'FWD', NULL),
('Emilio Butragueño', 'Spain', 'Retired', 'FWD', NULL),
('Ruud Gullit', 'Netherlands', 'Retired', 'MID', NULL),
('Paulo Futre', 'Portugal', 'Retired', 'FWD', NULL),
('Marco van Basten', 'Netherlands', 'Retired', 'FWD', NULL),
('Frank Rijkaard', 'Netherlands', 'Retired', 'MID', NULL),
('Franco Baresi', 'Italy', 'Retired', 'DEF', NULL),
('Lothar Matthäus', 'Germany', 'Retired', 'MID', NULL),
('Salvatore Schillaci', 'Italy', 'Retired', 'FWD', NULL),
('Andreas Brehme', 'Germany', 'Retired', 'DEF', NULL),
('Jean-Pierre Papin', 'France', 'Retired', 'FWD', NULL),
('Dejan Savićević', 'Yugoslavia', 'Retired', 'MID', NULL),
('Dennis Bergkamp', 'Netherlands', 'Retired', 'FWD', NULL),
('Éric Cantona', 'France', 'Retired', 'FWD', NULL),
('Jürgen Klinsmann', 'Germany', 'Retired', 'FWD', NULL),
('Jari Litmanen', 'Finland', 'Retired', 'MID', NULL),
('Matthias Sammer', 'Germany', 'Retired', 'DEF', NULL),
('Alan Shearer', 'England', 'Retired', 'FWD', NULL),
('Predrag Mijatović', 'Yugoslavia', 'Retired', 'FWD', NULL),
('Davor Šuker', 'Croatia', 'Retired', 'FWD', NULL)
ON CONFLICT DO NOTHING;

-- Insert all ceremonies (1956-2025, skip 2020)
INSERT INTO ceremonies (year, winner_id) VALUES
(1956, (SELECT id FROM players WHERE name = 'Stanley Matthews' LIMIT 1)),
(1957, (SELECT id FROM players WHERE name = 'Alfredo Di Stéfano' LIMIT 1)),
(1958, (SELECT id FROM players WHERE name = 'Raymond Kopa' LIMIT 1)),
(1959, (SELECT id FROM players WHERE name = 'Alfredo Di Stéfano' LIMIT 1)),
(1960, (SELECT id FROM players WHERE name = 'Luis Suárez Miramontes' LIMIT 1)),
(1961, (SELECT id FROM players WHERE name = 'Omar Sívori' LIMIT 1)),
(1962, (SELECT id FROM players WHERE name = 'Josef Masopust' LIMIT 1)),
(1963, (SELECT id FROM players WHERE name = 'Lev Yashin' LIMIT 1)),
(1964, (SELECT id FROM players WHERE name = 'Denis Law' LIMIT 1)),
(1965, (SELECT id FROM players WHERE name = 'Eusébio da Silva' LIMIT 1)),
(1966, (SELECT id FROM players WHERE name = 'Bobby Charlton' LIMIT 1)),
(1967, (SELECT id FROM players WHERE name = 'Flórian Albert' LIMIT 1)),
(1968, (SELECT id FROM players WHERE name = 'George Best' LIMIT 1)),
(1969, (SELECT id FROM players WHERE name = 'Gianni Rivera' LIMIT 1)),
(1970, (SELECT id FROM players WHERE name = 'Gerd Müller' LIMIT 1)),
(1971, (SELECT id FROM players WHERE name = 'Johan Cruyff' LIMIT 1)),
(1972, (SELECT id FROM players WHERE name = 'Franz Beckenbauer' LIMIT 1)),
(1973, (SELECT id FROM players WHERE name = 'Johan Cruyff' LIMIT 1)),
(1974, (SELECT id FROM players WHERE name = 'Johan Cruyff' LIMIT 1)),
(1975, (SELECT id FROM players WHERE name = 'Oleg Blokhin' LIMIT 1)),
(1976, (SELECT id FROM players WHERE name = 'Franz Beckenbauer' LIMIT 1)),
(1977, (SELECT id FROM players WHERE name = 'Allan Simonsen' LIMIT 1)),
(1978, (SELECT id FROM players WHERE name = 'Kevin Keegan' LIMIT 1)),
(1979, (SELECT id FROM players WHERE name = 'Kevin Keegan' LIMIT 1)),
(1980, (SELECT id FROM players WHERE name = 'Karl-Heinz Rummenigge' LIMIT 1)),
(1981, (SELECT id FROM players WHERE name = 'Karl-Heinz Rummenigge' LIMIT 1)),
(1982, (SELECT id FROM players WHERE name = 'Paolo Rossi' LIMIT 1)),
(1983, (SELECT id FROM players WHERE name = 'Michel Platini' LIMIT 1)),
(1984, (SELECT id FROM players WHERE name = 'Michel Platini' LIMIT 1)),
(1985, (SELECT id FROM players WHERE name = 'Michel Platini' LIMIT 1)),
(1986, (SELECT id FROM players WHERE name = 'Igor Belanov' LIMIT 1)),
(1987, (SELECT id FROM players WHERE name = 'Ruud Gullit' LIMIT 1)),
(1988, (SELECT id FROM players WHERE name = 'Marco van Basten' LIMIT 1)),
(1989, (SELECT id FROM players WHERE name = 'Marco van Basten' LIMIT 1)),
(1990, (SELECT id FROM players WHERE name = 'Lothar Matthäus' LIMIT 1)),
(1991, (SELECT id FROM players WHERE name = 'Jean-Pierre Papin' LIMIT 1)),
(1992, (SELECT id FROM players WHERE name = 'Marco van Basten' LIMIT 1)),
(1993, (SELECT id FROM players WHERE name = 'Roberto Baggio' LIMIT 1)),
(1994, (SELECT id FROM players WHERE name = 'Hristo Stoichkov' LIMIT 1)),
(1995, (SELECT id FROM players WHERE name = 'George Weah' LIMIT 1)),
(1996, (SELECT id FROM players WHERE name = 'Matthias Sammer' LIMIT 1)),
(1997, (SELECT id FROM players WHERE name = 'Ronaldo Nazário' LIMIT 1)),
(1998, (SELECT id FROM players WHERE name = 'Zinedine Zidane' LIMIT 1)),
(1999, (SELECT id FROM players WHERE name = 'Rivaldo' LIMIT 1)),
(2000, (SELECT id FROM players WHERE name = 'Luis Figo' LIMIT 1)),
(2001, (SELECT id FROM players WHERE name = 'Michael Owen' LIMIT 1)),
(2002, (SELECT id FROM players WHERE name = 'Ronaldo Nazário' LIMIT 1)),
(2003, (SELECT id FROM players WHERE name = 'Pavel Nedvěd' LIMIT 1)),
(2004, (SELECT id FROM players WHERE name = 'Andriy Shevchenko' LIMIT 1)),
(2005, (SELECT id FROM players WHERE name = 'Ronaldinho' LIMIT 1)),
(2006, (SELECT id FROM players WHERE name = 'Fabio Cannavaro' LIMIT 1)),
(2007, (SELECT id FROM players WHERE name = 'Kaká' LIMIT 1)),
(2008, (SELECT id FROM players WHERE name = 'Cristiano Ronaldo' LIMIT 1)),
(2009, (SELECT id FROM players WHERE name = 'Lionel Messi' LIMIT 1)),
(2010, (SELECT id FROM players WHERE name = 'Lionel Messi' LIMIT 1)),
(2011, (SELECT id FROM players WHERE name = 'Lionel Messi' LIMIT 1)),
(2012, (SELECT id FROM players WHERE name = 'Lionel Messi' LIMIT 1)),
(2013, (SELECT id FROM players WHERE name = 'Cristiano Ronaldo' LIMIT 1)),
(2014, (SELECT id FROM players WHERE name = 'Cristiano Ronaldo' LIMIT 1)),
(2015, (SELECT id FROM players WHERE name = 'Lionel Messi' LIMIT 1)),
(2016, (SELECT id FROM players WHERE name = 'Cristiano Ronaldo' LIMIT 1)),
(2017, (SELECT id FROM players WHERE name = 'Cristiano Ronaldo' LIMIT 1)),
(2018, (SELECT id FROM players WHERE name = 'Luka Modrić' LIMIT 1)),
(2019, (SELECT id FROM players WHERE name = 'Lionel Messi' LIMIT 1)),
(2021, (SELECT id FROM players WHERE name = 'Lionel Messi' LIMIT 1)),
(2022, (SELECT id FROM players WHERE name = 'Karim Benzema' LIMIT 1)),
(2023, (SELECT id FROM players WHERE name = 'Lionel Messi' LIMIT 1)),
(2024, (SELECT id FROM players WHERE name = 'Rodri' LIMIT 1)),
(2025, (SELECT id FROM players WHERE name = 'Ousmane Dembélé' LIMIT 1));

-- Insert nominations (rank 1, 2, 3 minimum for each year)
INSERT INTO nominations (ceremony_id, player_id, rank, votes_received) VALUES
-- 1956
((SELECT id FROM ceremonies WHERE year = 1956 LIMIT 1), (SELECT id FROM players WHERE name = 'Stanley Matthews' LIMIT 1), 1, 0),
((SELECT id FROM ceremonies WHERE year = 1956 LIMIT 1), (SELECT id FROM players WHERE name = 'Alfredo Di Stéfano' LIMIT 1), 2, 0),
((SELECT id FROM ceremonies WHERE year = 1956 LIMIT 1), (SELECT id FROM players WHERE name = 'Raymond Kopa' LIMIT 1), 3, 0),
-- 1957
((SELECT id FROM ceremonies WHERE year = 1957 LIMIT 1), (SELECT id FROM players WHERE name = 'Alfredo Di Stéfano' LIMIT 1), 1, 0),
((SELECT id FROM ceremonies WHERE year = 1957 LIMIT 1), (SELECT id FROM players WHERE name = 'Billy Wright' LIMIT 1), 2, 0),
((SELECT id FROM ceremonies WHERE year = 1957 LIMIT 1), (SELECT id FROM players WHERE name = 'Raymond Kopa' LIMIT 1), 3, 0),
-- 1958
((SELECT id FROM ceremonies WHERE year = 1958 LIMIT 1), (SELECT id FROM players WHERE name = 'Raymond Kopa' LIMIT 1), 1, 0),
((SELECT id FROM ceremonies WHERE year = 1958 LIMIT 1), (SELECT id FROM players WHERE name = 'Helmut Rahn' LIMIT 1), 2, 0),
((SELECT id FROM ceremonies WHERE year = 1958 LIMIT 1), (SELECT id FROM players WHERE name = 'Just Fontaine' LIMIT 1), 3, 0),
-- 1959
((SELECT id FROM ceremonies WHERE year = 1959 LIMIT 1), (SELECT id FROM players WHERE name = 'Alfredo Di Stéfano' LIMIT 1), 1, 0),
((SELECT id FROM ceremonies WHERE year = 1959 LIMIT 1), (SELECT id FROM players WHERE name = 'Raymond Kopa' LIMIT 1), 2, 0),
((SELECT id FROM ceremonies WHERE year = 1959 LIMIT 1), (SELECT id FROM players WHERE name = 'John Charles' LIMIT 1), 3, 0),
-- 1960
((SELECT id FROM ceremonies WHERE year = 1960 LIMIT 1), (SELECT id FROM players WHERE name = 'Luis Suárez Miramontes' LIMIT 1), 1, 0),
((SELECT id FROM ceremonies WHERE year = 1960 LIMIT 1), (SELECT id FROM players WHERE name = 'Ferenc Puskás' LIMIT 1), 2, 0),
((SELECT id FROM ceremonies WHERE year = 1960 LIMIT 1), (SELECT id FROM players WHERE name = 'Uwe Seeler' LIMIT 1), 3, 0),
-- 1961
((SELECT id FROM ceremonies WHERE year = 1961 LIMIT 1), (SELECT id FROM players WHERE name = 'Omar Sívori' LIMIT 1), 1, 0),
((SELECT id FROM ceremonies WHERE year = 1961 LIMIT 1), (SELECT id FROM players WHERE name = 'Luis Suárez Miramontes' LIMIT 1), 2, 0),
((SELECT id FROM ceremonies WHERE year = 1961 LIMIT 1), (SELECT id FROM players WHERE name = 'Johnny Haynes' LIMIT 1), 3, 0),
-- 1962
((SELECT id FROM ceremonies WHERE year = 1962 LIMIT 1), (SELECT id FROM players WHERE name = 'Josef Masopust' LIMIT 1), 1, 0),
((SELECT id FROM ceremonies WHERE year = 1962 LIMIT 1), (SELECT id FROM players WHERE name = 'Eusébio' LIMIT 1), 2, 0),
((SELECT id FROM ceremonies WHERE year = 1962 LIMIT 1), (SELECT id FROM players WHERE name = 'Karl-Heinz Schnellinger' LIMIT 1), 3, 0),
-- 1963
((SELECT id FROM ceremonies WHERE year = 1963 LIMIT 1), (SELECT id FROM players WHERE name = 'Lev Yashin' LIMIT 1), 1, 0),
((SELECT id FROM ceremonies WHERE year = 1963 LIMIT 1), (SELECT id FROM players WHERE name = 'Gianni Rivera' LIMIT 1), 2, 0),
((SELECT id FROM ceremonies WHERE year = 1963 LIMIT 1), (SELECT id FROM players WHERE name = 'Jimmy Greaves' LIMIT 1), 3, 0),
-- 1964
((SELECT id FROM ceremonies WHERE year = 1964 LIMIT 1), (SELECT id FROM players WHERE name = 'Denis Law' LIMIT 1), 1, 0),
((SELECT id FROM ceremonies WHERE year = 1964 LIMIT 1), (SELECT id FROM players WHERE name = 'Luis Suárez Miramontes' LIMIT 1), 2, 0),
((SELECT id FROM ceremonies WHERE year = 1964 LIMIT 1), (SELECT id FROM players WHERE name = 'Amancio Amaro' LIMIT 1), 3, 0),
-- 1965
((SELECT id FROM ceremonies WHERE year = 1965 LIMIT 1), (SELECT id FROM players WHERE name = 'Eusébio da Silva' LIMIT 1), 1, 0),
((SELECT id FROM ceremonies WHERE year = 1965 LIMIT 1), (SELECT id FROM players WHERE name = 'Giacinto Facchetti' LIMIT 1), 2, 0),
((SELECT id FROM ceremonies WHERE year = 1965 LIMIT 1), (SELECT id FROM players WHERE name = 'Luis Suárez Miramontes' LIMIT 1), 3, 0),
-- 1966
((SELECT id FROM ceremonies WHERE year = 1966 LIMIT 1), (SELECT id FROM players WHERE name = 'Bobby Charlton' LIMIT 1), 1, 0),
((SELECT id FROM ceremonies WHERE year = 1966 LIMIT 1), (SELECT id FROM players WHERE name = 'Eusébio da Silva' LIMIT 1), 2, 0),
((SELECT id FROM ceremonies WHERE year = 1966 LIMIT 1), (SELECT id FROM players WHERE name = 'Franz Beckenbauer' LIMIT 1), 3, 0),
-- 1967
((SELECT id FROM ceremonies WHERE year = 1967 LIMIT 1), (SELECT id FROM players WHERE name = 'Flórian Albert' LIMIT 1), 1, 0),
((SELECT id FROM ceremonies WHERE year = 1967 LIMIT 1), (SELECT id FROM players WHERE name = 'Bobby Charlton' LIMIT 1), 2, 0),
((SELECT id FROM ceremonies WHERE year = 1967 LIMIT 1), (SELECT id FROM players WHERE name = 'Jimmy Johnstone' LIMIT 1), 3, 0),
-- 1968
((SELECT id FROM ceremonies WHERE year = 1968 LIMIT 1), (SELECT id FROM players WHERE name = 'George Best' LIMIT 1), 1, 0),
((SELECT id FROM ceremonies WHERE year = 1968 LIMIT 1), (SELECT id FROM players WHERE name = 'Bobby Charlton' LIMIT 1), 2, 0),
((SELECT id FROM ceremonies WHERE year = 1968 LIMIT 1), (SELECT id FROM players WHERE name = 'Dragan Džajić' LIMIT 1), 3, 0),
-- 1969
((SELECT id FROM ceremonies WHERE year = 1969 LIMIT 1), (SELECT id FROM players WHERE name = 'Gianni Rivera' LIMIT 1), 1, 0),
((SELECT id FROM ceremonies WHERE year = 1969 LIMIT 1), (SELECT id FROM players WHERE name = 'Luigi Riva' LIMIT 1), 2, 0),
((SELECT id FROM ceremonies WHERE year = 1969 LIMIT 1), (SELECT id FROM players WHERE name = 'Gerd Müller' LIMIT 1), 3, 0),
-- 1970
((SELECT id FROM ceremonies WHERE year = 1970 LIMIT 1), (SELECT id FROM players WHERE name = 'Gerd Müller' LIMIT 1), 1, 0),
((SELECT id FROM ceremonies WHERE year = 1970 LIMIT 1), (SELECT id FROM players WHERE name = 'Bobby Moore' LIMIT 1), 2, 0),
((SELECT id FROM ceremonies WHERE year = 1970 LIMIT 1), (SELECT id FROM players WHERE name = 'Luigi Riva' LIMIT 1), 3, 0),
-- 1971
((SELECT id FROM ceremonies WHERE year = 1971 LIMIT 1), (SELECT id FROM players WHERE name = 'Johan Cruyff' LIMIT 1), 1, 0),
((SELECT id FROM ceremonies WHERE year = 1971 LIMIT 1), (SELECT id FROM players WHERE name = 'Sandro Mazzola' LIMIT 1), 2, 0),
((SELECT id FROM ceremonies WHERE year = 1971 LIMIT 1), (SELECT id FROM players WHERE name = 'George Best' LIMIT 1), 3, 0),
-- 1972
((SELECT id FROM ceremonies WHERE year = 1972 LIMIT 1), (SELECT id FROM players WHERE name = 'Franz Beckenbauer' LIMIT 1), 1, 0),
((SELECT id FROM ceremonies WHERE year = 1972 LIMIT 1), (SELECT id FROM players WHERE name = 'Gerd Müller' LIMIT 1), 2, 0),
((SELECT id FROM ceremonies WHERE year = 1972 LIMIT 1), (SELECT id FROM players WHERE name = 'Günter Netzer' LIMIT 1), 3, 0),
-- 1973
((SELECT id FROM ceremonies WHERE year = 1973 LIMIT 1), (SELECT id FROM players WHERE name = 'Johan Cruyff' LIMIT 1), 1, 0),
((SELECT id FROM ceremonies WHERE year = 1973 LIMIT 1), (SELECT id FROM players WHERE name = 'Dino Zoff' LIMIT 1), 2, 0),
((SELECT id FROM ceremonies WHERE year = 1973 LIMIT 1), (SELECT id FROM players WHERE name = 'Gerd Müller' LIMIT 1), 3, 0),
-- 1974
((SELECT id FROM ceremonies WHERE year = 1974 LIMIT 1), (SELECT id FROM players WHERE name = 'Johan Cruyff' LIMIT 1), 1, 0),
((SELECT id FROM ceremonies WHERE year = 1974 LIMIT 1), (SELECT id FROM players WHERE name = 'Franz Beckenbauer' LIMIT 1), 2, 0),
((SELECT id FROM ceremonies WHERE year = 1974 LIMIT 1), (SELECT id FROM players WHERE name = 'Kazimierz Deyna' LIMIT 1), 3, 0),
-- 1975
((SELECT id FROM ceremonies WHERE year = 1975 LIMIT 1), (SELECT id FROM players WHERE name = 'Oleg Blokhin' LIMIT 1), 1, 0),
((SELECT id FROM ceremonies WHERE year = 1975 LIMIT 1), (SELECT id FROM players WHERE name = 'Franz Beckenbauer' LIMIT 1), 2, 0),
((SELECT id FROM ceremonies WHERE year = 1975 LIMIT 1), (SELECT id FROM players WHERE name = 'Johan Cruyff' LIMIT 1), 3, 0),
-- 1976
((SELECT id FROM ceremonies WHERE year = 1976 LIMIT 1), (SELECT id FROM players WHERE name = 'Franz Beckenbauer' LIMIT 1), 1, 0),
((SELECT id FROM ceremonies WHERE year = 1976 LIMIT 1), (SELECT id FROM players WHERE name = 'Rob Rensenbrink' LIMIT 1), 2, 0),
((SELECT id FROM ceremonies WHERE year = 1976 LIMIT 1), (SELECT id FROM players WHERE name = 'Ivo Viktor' LIMIT 1), 3, 0),
-- 1977
((SELECT id FROM ceremonies WHERE year = 1977 LIMIT 1), (SELECT id FROM players WHERE name = 'Allan Simonsen' LIMIT 1), 1, 0),
((SELECT id FROM ceremonies WHERE year = 1977 LIMIT 1), (SELECT id FROM players WHERE name = 'Kevin Keegan' LIMIT 1), 2, 0),
((SELECT id FROM ceremonies WHERE year = 1977 LIMIT 1), (SELECT id FROM players WHERE name = 'Michel Platini' LIMIT 1), 3, 0),
-- 1978
((SELECT id FROM ceremonies WHERE year = 1978 LIMIT 1), (SELECT id FROM players WHERE name = 'Kevin Keegan' LIMIT 1), 1, 0),
((SELECT id FROM ceremonies WHERE year = 1978 LIMIT 1), (SELECT id FROM players WHERE name = 'Hans Krankl' LIMIT 1), 2, 0),
((SELECT id FROM ceremonies WHERE year = 1978 LIMIT 1), (SELECT id FROM players WHERE name = 'Rob Rensenbrink' LIMIT 1), 3, 0),
-- 1979
((SELECT id FROM ceremonies WHERE year = 1979 LIMIT 1), (SELECT id FROM players WHERE name = 'Kevin Keegan' LIMIT 1), 1, 0),
((SELECT id FROM ceremonies WHERE year = 1979 LIMIT 1), (SELECT id FROM players WHERE name = 'Karl-Heinz Rummenigge' LIMIT 1), 2, 0),
((SELECT id FROM ceremonies WHERE year = 1979 LIMIT 1), (SELECT id FROM players WHERE name = 'Ruud Krol' LIMIT 1), 3, 0),
-- 1980
((SELECT id FROM ceremonies WHERE year = 1980 LIMIT 1), (SELECT id FROM players WHERE name = 'Karl-Heinz Rummenigge' LIMIT 1), 1, 0),
((SELECT id FROM ceremonies WHERE year = 1980 LIMIT 1), (SELECT id FROM players WHERE name = 'Bernd Schuster' LIMIT 1), 2, 0),
((SELECT id FROM ceremonies WHERE year = 1980 LIMIT 1), (SELECT id FROM players WHERE name = 'Michel Platini' LIMIT 1), 3, 0),
-- 1981
((SELECT id FROM ceremonies WHERE year = 1981 LIMIT 1), (SELECT id FROM players WHERE name = 'Karl-Heinz Rummenigge' LIMIT 1), 1, 0),
((SELECT id FROM ceremonies WHERE year = 1981 LIMIT 1), (SELECT id FROM players WHERE name = 'Paul Breitner' LIMIT 1), 2, 0),
((SELECT id FROM ceremonies WHERE year = 1981 LIMIT 1), (SELECT id FROM players WHERE name = 'Bernd Schuster' LIMIT 1), 3, 0),
-- 1982
((SELECT id FROM ceremonies WHERE year = 1982 LIMIT 1), (SELECT id FROM players WHERE name = 'Paolo Rossi' LIMIT 1), 1, 0),
((SELECT id FROM ceremonies WHERE year = 1982 LIMIT 1), (SELECT id FROM players WHERE name = 'Alain Giresse' LIMIT 1), 2, 0),
((SELECT id FROM ceremonies WHERE year = 1982 LIMIT 1), (SELECT id FROM players WHERE name = 'Zbigniew Boniek' LIMIT 1), 3, 0),
-- 1983
((SELECT id FROM ceremonies WHERE year = 1983 LIMIT 1), (SELECT id FROM players WHERE name = 'Michel Platini' LIMIT 1), 1, 0),
((SELECT id FROM ceremonies WHERE year = 1983 LIMIT 1), (SELECT id FROM players WHERE name = 'Kenny Dalglish' LIMIT 1), 2, 0),
((SELECT id FROM ceremonies WHERE year = 1983 LIMIT 1), (SELECT id FROM players WHERE name = 'Allan Simonsen' LIMIT 1), 3, 0),
-- 1984
((SELECT id FROM ceremonies WHERE year = 1984 LIMIT 1), (SELECT id FROM players WHERE name = 'Michel Platini' LIMIT 1), 1, 0),
((SELECT id FROM ceremonies WHERE year = 1984 LIMIT 1), (SELECT id FROM players WHERE name = 'Jean Tigana' LIMIT 1), 2, 0),
((SELECT id FROM ceremonies WHERE year = 1984 LIMIT 1), (SELECT id FROM players WHERE name = 'Preben Elkjær' LIMIT 1), 3, 0),
-- 1985
((SELECT id FROM ceremonies WHERE year = 1985 LIMIT 1), (SELECT id FROM players WHERE name = 'Michel Platini' LIMIT 1), 1, 0),
((SELECT id FROM ceremonies WHERE year = 1985 LIMIT 1), (SELECT id FROM players WHERE name = 'Preben Elkjær' LIMIT 1), 2, 0),
((SELECT id FROM ceremonies WHERE year = 1985 LIMIT 1), (SELECT id FROM players WHERE name = 'Bernd Schuster' LIMIT 1), 3, 0),
-- 1986
((SELECT id FROM ceremonies WHERE year = 1986 LIMIT 1), (SELECT id FROM players WHERE name = 'Igor Belanov' LIMIT 1), 1, 0),
((SELECT id FROM ceremonies WHERE year = 1986 LIMIT 1), (SELECT id FROM players WHERE name = 'Gary Lineker' LIMIT 1), 2, 0),
((SELECT id FROM ceremonies WHERE year = 1986 LIMIT 1), (SELECT id FROM players WHERE name = 'Emilio Butragueño' LIMIT 1), 3, 0),
-- 1987
((SELECT id FROM ceremonies WHERE year = 1987 LIMIT 1), (SELECT id FROM players WHERE name = 'Ruud Gullit' LIMIT 1), 1, 0),
((SELECT id FROM ceremonies WHERE year = 1987 LIMIT 1), (SELECT id FROM players WHERE name = 'Paulo Futre' LIMIT 1), 2, 0),
((SELECT id FROM ceremonies WHERE year = 1987 LIMIT 1), (SELECT id FROM players WHERE name = 'Emilio Butragueño' LIMIT 1), 3, 0),
-- 1988
((SELECT id FROM ceremonies WHERE year = 1988 LIMIT 1), (SELECT id FROM players WHERE name = 'Marco van Basten' LIMIT 1), 1, 0),
((SELECT id FROM ceremonies WHERE year = 1988 LIMIT 1), (SELECT id FROM players WHERE name = 'Ruud Gullit' LIMIT 1), 2, 0),
((SELECT id FROM ceremonies WHERE year = 1988 LIMIT 1), (SELECT id FROM players WHERE name = 'Frank Rijkaard' LIMIT 1), 3, 0),
-- 1989
((SELECT id FROM ceremonies WHERE year = 1989 LIMIT 1), (SELECT id FROM players WHERE name = 'Marco van Basten' LIMIT 1), 1, 0),
((SELECT id FROM ceremonies WHERE year = 1989 LIMIT 1), (SELECT id FROM players WHERE name = 'Franco Baresi' LIMIT 1), 2, 0),
((SELECT id FROM ceremonies WHERE year = 1989 LIMIT 1), (SELECT id FROM players WHERE name = 'Frank Rijkaard' LIMIT 1), 3, 0),
-- 1990
((SELECT id FROM ceremonies WHERE year = 1990 LIMIT 1), (SELECT id FROM players WHERE name = 'Lothar Matthäus' LIMIT 1), 1, 0),
((SELECT id FROM ceremonies WHERE year = 1990 LIMIT 1), (SELECT id FROM players WHERE name = 'Salvatore Schillaci' LIMIT 1), 2, 0),
((SELECT id FROM ceremonies WHERE year = 1990 LIMIT 1), (SELECT id FROM players WHERE name = 'Andreas Brehme' LIMIT 1), 3, 0),
-- 1991
((SELECT id FROM ceremonies WHERE year = 1991 LIMIT 1), (SELECT id FROM players WHERE name = 'Jean-Pierre Papin' LIMIT 1), 1, 0),
((SELECT id FROM ceremonies WHERE year = 1991 LIMIT 1), (SELECT id FROM players WHERE name = 'Dejan Savićević' LIMIT 1), 2, 0),
((SELECT id FROM ceremonies WHERE year = 1991 LIMIT 1), (SELECT id FROM players WHERE name = 'Lothar Matthäus' LIMIT 1), 3, 0),
-- 1992
((SELECT id FROM ceremonies WHERE year = 1992 LIMIT 1), (SELECT id FROM players WHERE name = 'Marco van Basten' LIMIT 1), 1, 0),
((SELECT id FROM ceremonies WHERE year = 1992 LIMIT 1), (SELECT id FROM players WHERE name = 'Hristo Stoichkov' LIMIT 1), 2, 0),
((SELECT id FROM ceremonies WHERE year = 1992 LIMIT 1), (SELECT id FROM players WHERE name = 'Dennis Bergkamp' LIMIT 1), 3, 0),
-- 1993
((SELECT id FROM ceremonies WHERE year = 1993 LIMIT 1), (SELECT id FROM players WHERE name = 'Roberto Baggio' LIMIT 1), 1, 0),
((SELECT id FROM ceremonies WHERE year = 1993 LIMIT 1), (SELECT id FROM players WHERE name = 'Dennis Bergkamp' LIMIT 1), 2, 0),
((SELECT id FROM ceremonies WHERE year = 1993 LIMIT 1), (SELECT id FROM players WHERE name = 'Éric Cantona' LIMIT 1), 3, 0),
-- 1994
((SELECT id FROM ceremonies WHERE year = 1994 LIMIT 1), (SELECT id FROM players WHERE name = 'Hristo Stoichkov' LIMIT 1), 1, 0),
((SELECT id FROM ceremonies WHERE year = 1994 LIMIT 1), (SELECT id FROM players WHERE name = 'Roberto Baggio' LIMIT 1), 2, 0),
((SELECT id FROM ceremonies WHERE year = 1994 LIMIT 1), (SELECT id FROM players WHERE name = 'Paolo Maldini' LIMIT 1), 3, 0),
-- 1995
((SELECT id FROM ceremonies WHERE year = 1995 LIMIT 1), (SELECT id FROM players WHERE name = 'George Weah' LIMIT 1), 1, 0),
((SELECT id FROM ceremonies WHERE year = 1995 LIMIT 1), (SELECT id FROM players WHERE name = 'Jürgen Klinsmann' LIMIT 1), 2, 0),
((SELECT id FROM ceremonies WHERE year = 1995 LIMIT 1), (SELECT id FROM players WHERE name = 'Jari Litmanen' LIMIT 1), 3, 0),
-- 1996
((SELECT id FROM ceremonies WHERE year = 1996 LIMIT 1), (SELECT id FROM players WHERE name = 'Matthias Sammer' LIMIT 1), 1, 0),
((SELECT id FROM ceremonies WHERE year = 1996 LIMIT 1), (SELECT id FROM players WHERE name = 'Ronaldo Nazário' LIMIT 1), 2, 0),
((SELECT id FROM ceremonies WHERE year = 1996 LIMIT 1), (SELECT id FROM players WHERE name = 'Alan Shearer' LIMIT 1), 3, 0),
-- 1997
((SELECT id FROM ceremonies WHERE year = 1997 LIMIT 1), (SELECT id FROM players WHERE name = 'Ronaldo Nazário' LIMIT 1), 1, 0),
((SELECT id FROM ceremonies WHERE year = 1997 LIMIT 1), (SELECT id FROM players WHERE name = 'Predrag Mijatović' LIMIT 1), 2, 0),
((SELECT id FROM ceremonies WHERE year = 1997 LIMIT 1), (SELECT id FROM players WHERE name = 'Zinedine Zidane' LIMIT 1), 3, 0),
-- 1998
((SELECT id FROM ceremonies WHERE year = 1998 LIMIT 1), (SELECT id FROM players WHERE name = 'Zinedine Zidane' LIMIT 1), 1, 0),
((SELECT id FROM ceremonies WHERE year = 1998 LIMIT 1), (SELECT id FROM players WHERE name = 'Davor Šuker' LIMIT 1), 2, 0),
((SELECT id FROM ceremonies WHERE year = 1998 LIMIT 1), (SELECT id FROM players WHERE name = 'Ronaldo Nazário' LIMIT 1), 3, 0),
-- 1999
((SELECT id FROM ceremonies WHERE year = 1999 LIMIT 1), (SELECT id FROM players WHERE name = 'Rivaldo' LIMIT 1), 1, 0),
((SELECT id FROM ceremonies WHERE year = 1999 LIMIT 1), (SELECT id FROM players WHERE name = 'David Beckham' LIMIT 1), 2, 0),
((SELECT id FROM ceremonies WHERE year = 1999 LIMIT 1), (SELECT id FROM players WHERE name = 'Andriy Shevchenko' LIMIT 1), 3, 0),
-- 2000
((SELECT id FROM ceremonies WHERE year = 2000 LIMIT 1), (SELECT id FROM players WHERE name = 'Luis Figo' LIMIT 1), 1, 0),
((SELECT id FROM ceremonies WHERE year = 2000 LIMIT 1), (SELECT id FROM players WHERE name = 'Zinedine Zidane' LIMIT 1), 2, 0),
((SELECT id FROM ceremonies WHERE year = 2000 LIMIT 1), (SELECT id FROM players WHERE name = 'Andriy Shevchenko' LIMIT 1), 3, 0),
-- 2001
((SELECT id FROM ceremonies WHERE year = 2001 LIMIT 1), (SELECT id FROM players WHERE name = 'Michael Owen' LIMIT 1), 1, 0),
((SELECT id FROM ceremonies WHERE year = 2001 LIMIT 1), (SELECT id FROM players WHERE name = 'Raúl González' LIMIT 1), 2, 0),
((SELECT id FROM ceremonies WHERE year = 2001 LIMIT 1), (SELECT id FROM players WHERE name = 'Oliver Kahn' LIMIT 1), 3, 0),
-- 2002
((SELECT id FROM ceremonies WHERE year = 2002 LIMIT 1), (SELECT id FROM players WHERE name = 'Ronaldo Nazário' LIMIT 1), 1, 0),
((SELECT id FROM ceremonies WHERE year = 2002 LIMIT 1), (SELECT id FROM players WHERE name = 'Roberto Carlos' LIMIT 1), 2, 0),
((SELECT id FROM ceremonies WHERE year = 2002 LIMIT 1), (SELECT id FROM players WHERE name = 'Oliver Kahn' LIMIT 1), 3, 0),
-- 2003
((SELECT id FROM ceremonies WHERE year = 2003 LIMIT 1), (SELECT id FROM players WHERE name = 'Pavel Nedvěd' LIMIT 1), 1, 0),
((SELECT id FROM ceremonies WHERE year = 2003 LIMIT 1), (SELECT id FROM players WHERE name = 'Thierry Henry' LIMIT 1), 2, 0),
((SELECT id FROM ceremonies WHERE year = 2003 LIMIT 1), (SELECT id FROM players WHERE name = 'Paolo Maldini' LIMIT 1), 3, 0),
-- 2004
((SELECT id FROM ceremonies WHERE year = 2004 LIMIT 1), (SELECT id FROM players WHERE name = 'Andriy Shevchenko' LIMIT 1), 1, 0),
((SELECT id FROM ceremonies WHERE year = 2004 LIMIT 1), (SELECT id FROM players WHERE name = 'Deco' LIMIT 1), 2, 0),
((SELECT id FROM ceremonies WHERE year = 2004 LIMIT 1), (SELECT id FROM players WHERE name = 'Ronaldinho' LIMIT 1), 3, 0),
-- 2005
((SELECT id FROM ceremonies WHERE year = 2005 LIMIT 1), (SELECT id FROM players WHERE name = 'Ronaldinho' LIMIT 1), 1, 0),
((SELECT id FROM ceremonies WHERE year = 2005 LIMIT 1), (SELECT id FROM players WHERE name = 'Frank Lampard' LIMIT 1), 2, 0),
((SELECT id FROM ceremonies WHERE year = 2005 LIMIT 1), (SELECT id FROM players WHERE name = 'Steven Gerrard' LIMIT 1), 3, 0),
-- 2006
((SELECT id FROM ceremonies WHERE year = 2006 LIMIT 1), (SELECT id FROM players WHERE name = 'Fabio Cannavaro' LIMIT 1), 1, 0),
((SELECT id FROM ceremonies WHERE year = 2006 LIMIT 1), (SELECT id FROM players WHERE name = 'Gianluigi Buffon' LIMIT 1), 2, 0),
((SELECT id FROM ceremonies WHERE year = 2006 LIMIT 1), (SELECT id FROM players WHERE name = 'Thierry Henry' LIMIT 1), 3, 0),
-- 2007
((SELECT id FROM ceremonies WHERE year = 2007 LIMIT 1), (SELECT id FROM players WHERE name = 'Kaká' LIMIT 1), 1, 0),
((SELECT id FROM ceremonies WHERE year = 2007 LIMIT 1), (SELECT id FROM players WHERE name = 'Cristiano Ronaldo' LIMIT 1), 2, 0),
((SELECT id FROM ceremonies WHERE year = 2007 LIMIT 1), (SELECT id FROM players WHERE name = 'Lionel Messi' LIMIT 1), 3, 0),
-- 2008
((SELECT id FROM ceremonies WHERE year = 2008 LIMIT 1), (SELECT id FROM players WHERE name = 'Cristiano Ronaldo' LIMIT 1), 1, 0),
((SELECT id FROM ceremonies WHERE year = 2008 LIMIT 1), (SELECT id FROM players WHERE name = 'Lionel Messi' LIMIT 1), 2, 0),
((SELECT id FROM ceremonies WHERE year = 2008 LIMIT 1), (SELECT id FROM players WHERE name = 'Fernando Torres' LIMIT 1), 3, 0),
-- 2009
((SELECT id FROM ceremonies WHERE year = 2009 LIMIT 1), (SELECT id FROM players WHERE name = 'Lionel Messi' LIMIT 1), 1, 0),
((SELECT id FROM ceremonies WHERE year = 2009 LIMIT 1), (SELECT id FROM players WHERE name = 'Cristiano Ronaldo' LIMIT 1), 2, 0),
((SELECT id FROM ceremonies WHERE year = 2009 LIMIT 1), (SELECT id FROM players WHERE name = 'Xavi Hernández' LIMIT 1), 3, 0),
-- 2010
((SELECT id FROM ceremonies WHERE year = 2010 LIMIT 1), (SELECT id FROM players WHERE name = 'Lionel Messi' LIMIT 1), 1, 0),
((SELECT id FROM ceremonies WHERE year = 2010 LIMIT 1), (SELECT id FROM players WHERE name = 'Andrés Iniesta' LIMIT 1), 2, 0),
((SELECT id FROM ceremonies WHERE year = 2010 LIMIT 1), (SELECT id FROM players WHERE name = 'Xavi Hernández' LIMIT 1), 3, 0),
-- 2011
((SELECT id FROM ceremonies WHERE year = 2011 LIMIT 1), (SELECT id FROM players WHERE name = 'Lionel Messi' LIMIT 1), 1, 0),
((SELECT id FROM ceremonies WHERE year = 2011 LIMIT 1), (SELECT id FROM players WHERE name = 'Cristiano Ronaldo' LIMIT 1), 2, 0),
((SELECT id FROM ceremonies WHERE year = 2011 LIMIT 1), (SELECT id FROM players WHERE name = 'Xavi Hernández' LIMIT 1), 3, 0),
-- 2012
((SELECT id FROM ceremonies WHERE year = 2012 LIMIT 1), (SELECT id FROM players WHERE name = 'Lionel Messi' LIMIT 1), 1, 0),
((SELECT id FROM ceremonies WHERE year = 2012 LIMIT 1), (SELECT id FROM players WHERE name = 'Cristiano Ronaldo' LIMIT 1), 2, 0),
((SELECT id FROM ceremonies WHERE year = 2012 LIMIT 1), (SELECT id FROM players WHERE name = 'Andrés Iniesta' LIMIT 1), 3, 0),
-- 2013
((SELECT id FROM ceremonies WHERE year = 2013 LIMIT 1), (SELECT id FROM players WHERE name = 'Cristiano Ronaldo' LIMIT 1), 1, 0),
((SELECT id FROM ceremonies WHERE year = 2013 LIMIT 1), (SELECT id FROM players WHERE name = 'Lionel Messi' LIMIT 1), 2, 0),
((SELECT id FROM ceremonies WHERE year = 2013 LIMIT 1), (SELECT id FROM players WHERE name = 'Franck Ribéry' LIMIT 1), 3, 0),
-- 2014
((SELECT id FROM ceremonies WHERE year = 2014 LIMIT 1), (SELECT id FROM players WHERE name = 'Cristiano Ronaldo' LIMIT 1), 1, 0),
((SELECT id FROM ceremonies WHERE year = 2014 LIMIT 1), (SELECT id FROM players WHERE name = 'Lionel Messi' LIMIT 1), 2, 0),
((SELECT id FROM ceremonies WHERE year = 2014 LIMIT 1), (SELECT id FROM players WHERE name = 'Manuel Neuer' LIMIT 1), 3, 0),
-- 2015
((SELECT id FROM ceremonies WHERE year = 2015 LIMIT 1), (SELECT id FROM players WHERE name = 'Lionel Messi' LIMIT 1), 1, 0),
((SELECT id FROM ceremonies WHERE year = 2015 LIMIT 1), (SELECT id FROM players WHERE name = 'Cristiano Ronaldo' LIMIT 1), 2, 0),
((SELECT id FROM ceremonies WHERE year = 2015 LIMIT 1), (SELECT id FROM players WHERE name = 'Neymar' LIMIT 1), 3, 0),
-- 2016
((SELECT id FROM ceremonies WHERE year = 2016 LIMIT 1), (SELECT id FROM players WHERE name = 'Cristiano Ronaldo' LIMIT 1), 1, 0),
((SELECT id FROM ceremonies WHERE year = 2016 LIMIT 1), (SELECT id FROM players WHERE name = 'Lionel Messi' LIMIT 1), 2, 0),
((SELECT id FROM ceremonies WHERE year = 2016 LIMIT 1), (SELECT id FROM players WHERE name = 'Antoine Griezmann' LIMIT 1), 3, 0),
-- 2017
((SELECT id FROM ceremonies WHERE year = 2017 LIMIT 1), (SELECT id FROM players WHERE name = 'Cristiano Ronaldo' LIMIT 1), 1, 0),
((SELECT id FROM ceremonies WHERE year = 2017 LIMIT 1), (SELECT id FROM players WHERE name = 'Lionel Messi' LIMIT 1), 2, 0),
((SELECT id FROM ceremonies WHERE year = 2017 LIMIT 1), (SELECT id FROM players WHERE name = 'Neymar' LIMIT 1), 3, 0),
-- 2018
((SELECT id FROM ceremonies WHERE year = 2018 LIMIT 1), (SELECT id FROM players WHERE name = 'Luka Modrić' LIMIT 1), 1, 0),
((SELECT id FROM ceremonies WHERE year = 2018 LIMIT 1), (SELECT id FROM players WHERE name = 'Cristiano Ronaldo' LIMIT 1), 2, 0),
((SELECT id FROM ceremonies WHERE year = 2018 LIMIT 1), (SELECT id FROM players WHERE name = 'Antoine Griezmann' LIMIT 1), 3, 0),
-- 2019
((SELECT id FROM ceremonies WHERE year = 2019 LIMIT 1), (SELECT id FROM players WHERE name = 'Lionel Messi' LIMIT 1), 1, 0),
((SELECT id FROM ceremonies WHERE year = 2019 LIMIT 1), (SELECT id FROM players WHERE name = 'Virgil van Dijk' LIMIT 1), 2, 0),
((SELECT id FROM ceremonies WHERE year = 2019 LIMIT 1), (SELECT id FROM players WHERE name = 'Cristiano Ronaldo' LIMIT 1), 3, 0),
-- 2021
((SELECT id FROM ceremonies WHERE year = 2021 LIMIT 1), (SELECT id FROM players WHERE name = 'Lionel Messi' LIMIT 1), 1, 0),
((SELECT id FROM ceremonies WHERE year = 2021 LIMIT 1), (SELECT id FROM players WHERE name = 'Robert Lewandowski' LIMIT 1), 2, 0),
((SELECT id FROM ceremonies WHERE year = 2021 LIMIT 1), (SELECT id FROM players WHERE name = 'Jorginho' LIMIT 1), 3, 0),
-- 2022
((SELECT id FROM ceremonies WHERE year = 2022 LIMIT 1), (SELECT id FROM players WHERE name = 'Karim Benzema' LIMIT 1), 1, 0),
((SELECT id FROM ceremonies WHERE year = 2022 LIMIT 1), (SELECT id FROM players WHERE name = 'Sadio Mané' LIMIT 1), 2, 0),
((SELECT id FROM ceremonies WHERE year = 2022 LIMIT 1), (SELECT id FROM players WHERE name = 'Kevin De Bruyne' LIMIT 1), 3, 0),
-- 2023
((SELECT id FROM ceremonies WHERE year = 2023 LIMIT 1), (SELECT id FROM players WHERE name = 'Lionel Messi' LIMIT 1), 1, 0),
((SELECT id FROM ceremonies WHERE year = 2023 LIMIT 1), (SELECT id FROM players WHERE name = 'Erling Haaland' LIMIT 1), 2, 0),
((SELECT id FROM ceremonies WHERE year = 2023 LIMIT 1), (SELECT id FROM players WHERE name = 'Kylian Mbappé' LIMIT 1), 3, 0),
-- 2024
((SELECT id FROM ceremonies WHERE year = 2024 LIMIT 1), (SELECT id FROM players WHERE name = 'Rodri' LIMIT 1), 1, 0),
((SELECT id FROM ceremonies WHERE year = 2024 LIMIT 1), (SELECT id FROM players WHERE name = 'Vinícius Júnior' LIMIT 1), 2, 0),
((SELECT id FROM ceremonies WHERE year = 2024 LIMIT 1), (SELECT id FROM players WHERE name = 'Jude Bellingham' LIMIT 1), 3, 0),
-- 2025
((SELECT id FROM ceremonies WHERE year = 2025 LIMIT 1), (SELECT id FROM players WHERE name = 'Ousmane Dembélé' LIMIT 1), 1, 0),
((SELECT id FROM ceremonies WHERE year = 2025 LIMIT 1), (SELECT id FROM players WHERE name = 'Lamine Yamal' LIMIT 1), 2, 0),
((SELECT id FROM ceremonies WHERE year = 2025 LIMIT 1), (SELECT id FROM players WHERE name = 'Vitinha' LIMIT 1), 3, 0);
