-- Seed Players
INSERT INTO players (name, nationality, club, position, photo_url) VALUES
('Zinedine Zidane', 'France', 'Real Madrid', 'MID', 'https://upload.wikimedia.org/wikipedia/commons/thumb/f/f3/Zinedine_Zidane_by_Tasnim_03.jpg/400px-Zinedine_Zidane_by_Tasnim_03.jpg'),
('Rivaldo', 'Brazil', 'Barcelona', 'FWD', 'https://upload.wikimedia.org/wikipedia/commons/thumb/0/0e/Rivaldo_in_2013.jpg/400px-Rivaldo_in_2013.jpg'),
('Luis Figo', 'Portugal', 'Real Madrid', 'MID', 'https://upload.wikimedia.org/wikipedia/commons/thumb/c/c8/Luis_Figo_2012.jpg/400px-Luis_Figo_2012.jpg'),
('Michael Owen', 'England', 'Liverpool', 'FWD', 'https://upload.wikimedia.org/wikipedia/commons/thumb/1/1e/Michael_Owen_2010.jpg/400px-Michael_Owen_2010.jpg'),
('Ronaldo Nazário', 'Brazil', 'Real Madrid', 'FWD', 'https://upload.wikimedia.org/wikipedia/commons/thumb/b/b3/Ronaldo_Nazario_in_2018.jpg/400px-Ronaldo_Nazario_in_2018.jpg'),
('Pavel Nedvěd', 'Czech Republic', 'Juventus', 'MID', 'https://upload.wikimedia.org/wikipedia/commons/thumb/3/36/Pavel_Nedved_2011.jpg/400px-Pavel_Nedved_2011.jpg'),
('Ronaldinho', 'Brazil', 'Barcelona', 'FWD', 'https://upload.wikimedia.org/wikipedia/commons/thumb/7/70/Ronaldinho_11feb2007.jpg/400px-Ronaldinho_11feb2007.jpg'),
('Fabio Cannavaro', 'Italy', 'Real Madrid', 'DEF', 'https://upload.wikimedia.org/wikipedia/commons/thumb/3/31/Fabio_Cannavaro_2011.jpg/400px-Fabio_Cannavaro_2011.jpg'),
('Kaká', 'Brazil', 'AC Milan', 'MID', 'https://upload.wikimedia.org/wikipedia/commons/thumb/3/3d/Kak%C3%A1_2013.jpg/400px-Kak%C3%A1_2013.jpg'),
('Cristiano Ronaldo', 'Portugal', 'Real Madrid', 'FWD', 'https://upload.wikimedia.org/wikipedia/commons/thumb/8/8c/Cristiano_Ronaldo_2018.jpg/400px-Cristiano_Ronaldo_2018.jpg'),
('Lionel Messi', 'Argentina', 'Barcelona', 'FWD', 'https://upload.wikimedia.org/wikipedia/commons/thumb/c/c1/Lionel_Messi_20180626.jpg/400px-Lionel_Messi_20180626.jpg'),
('Luka Modrić', 'Croatia', 'Real Madrid', 'MID', 'https://upload.wikimedia.org/wikipedia/commons/thumb/e/e9/Luka_Modri%C4%87_2018.jpg/400px-Luka_Modri%C4%87_2018.jpg'),
('Karim Benzema', 'France', 'Real Madrid', 'FWD', 'https://upload.wikimedia.org/wikipedia/commons/thumb/3/3c/Karim_Benzema_2018.jpg/400px-Karim_Benzema_2018.jpg'),
('Rodri', 'Spain', 'Manchester City', 'MID', 'https://upload.wikimedia.org/wikipedia/commons/thumb/0/07/Rodri_2021.jpg/400px-Rodri_2021.jpg'),
('Ousmane Dembélé', 'France', 'PSG', 'FWD', 'https://upload.wikimedia.org/wikipedia/commons/thumb/d/d4/Ousmane_Demb%C3%A9l%C3%A9_2018.jpg/400px-Ousmane_Demb%C3%A9l%C3%A9_2018.jpg'),
('Lamine Yamal', 'Spain', 'Barcelona', 'FWD', 'https://upload.wikimedia.org/wikipedia/commons/thumb/e/e6/Lamine_Yamal_2024.jpg/400px-Lamine_Yamal_2024.jpg'),
('Vitinha', 'Portugal', 'PSG', 'MID', 'https://upload.wikimedia.org/wikipedia/commons/thumb/d/d6/Vitinha_2022.jpg/400px-Vitinha_2022.jpg'),
('Mohamed Salah', 'Egypt', 'Liverpool', 'FWD', 'https://upload.wikimedia.org/wikipedia/commons/thumb/4/4a/Mohamed_Salah_2018.jpg/400px-Mohamed_Salah_2018.jpg'),
('Raphinha', 'Brazil', 'Barcelona', 'FWD', 'https://upload.wikimedia.org/wikipedia/commons/thumb/d/d1/Raphinha_2022.jpg/400px-Raphinha_2022.jpg'),
('Achraf Hakimi', 'Morocco', 'PSG', 'DEF', 'https://upload.wikimedia.org/wikipedia/commons/thumb/a/a2/Achraf_Hakimi_2018.jpg/400px-Achraf_Hakimi_2018.jpg'),
('Kylian Mbappé', 'France', 'Real Madrid', 'FWD', 'https://upload.wikimedia.org/wikipedia/commons/thumb/5/57/Kylian_Mbapp%C3%A9_2018.jpg/400px-Kylian_Mbapp%C3%A9_2018.jpg'),
('Cole Palmer', 'England', 'Chelsea', 'MID', 'https://upload.wikimedia.org/wikipedia/commons/thumb/f/f6/Cole_Palmer_2023.jpg/400px-Cole_Palmer_2023.jpg'),
('Gianluigi Donnarumma', 'Italy', 'PSG', 'GK', 'https://upload.wikimedia.org/wikipedia/commons/thumb/3/3e/Gianluigi_Donnarumma_2021.jpg/400px-Gianluigi_Donnarumma_2021.jpg'),
('Nuno Mendes', 'Portugal', 'PSG', 'DEF', 'https://upload.wikimedia.org/wikipedia/commons/thumb/4/4e/Nuno_Mendes_2022.jpg/400px-Nuno_Mendes_2022.jpg'),
('Davor Šuker', 'Croatia', 'Real Madrid', 'FWD', NULL),
('Gabriel Batistuta', 'Argentina', 'Fiorentina', 'FWD', NULL),
('Thierry Henry', 'France', 'Arsenal', 'FWD', NULL),
('Andriy Shevchenko', 'Ukraine', 'AC Milan', 'FWD', NULL),
('David Beckham', 'England', 'Manchester United', 'MID', NULL),
('Raúl', 'Spain', 'Real Madrid', 'FWD', NULL),
('Oliver Kahn', 'Germany', 'Bayern Munich', 'GK', NULL),
('Roberto Carlos', 'Brazil', 'Real Madrid', 'DEF', NULL),
('Samuel Eto''o', 'Cameroon', 'Barcelona', 'FWD', NULL),
('Andrés Iniesta', 'Spain', 'Barcelona', 'MID', NULL),
('Xavi', 'Spain', 'Barcelona', 'MID', NULL),
('Franck Ribéry', 'France', 'Bayern Munich', 'FWD', NULL),
('Manuel Neuer', 'Germany', 'Bayern Munich', 'GK', NULL),
('Antoine Griezmann', 'France', 'Atletico Madrid', 'FWD', NULL),
('Neymar Jr', 'Brazil', 'PSG', 'FWD', NULL),
('Virgil van Dijk', 'Netherlands', 'Liverpool', 'DEF', NULL),
('Robert Lewandowski', 'Poland', 'Bayern Munich', 'FWD', NULL),
('Erling Haaland', 'Norway', 'Manchester City', 'FWD', NULL),
('Kevin De Bruyne', 'Belgium', 'Manchester City', 'MID', NULL),
('Vinícius Júnior', 'Brazil', 'Real Madrid', 'FWD', NULL),
('Jude Bellingham', 'England', 'Real Madrid', 'MID', NULL);

-- Seed Ceremonies (Winner ID matches players inserted above)
INSERT INTO ceremonies (year, winner_id) VALUES
(1998, (SELECT id FROM players WHERE name = 'Zinedine Zidane')),
(1999, (SELECT id FROM players WHERE name = 'Rivaldo')),
(2000, (SELECT id FROM players WHERE name = 'Luis Figo')),
(2001, (SELECT id FROM players WHERE name = 'Michael Owen')),
(2002, (SELECT id FROM players WHERE name = 'Ronaldo Nazário')),
(2003, (SELECT id FROM players WHERE name = 'Pavel Nedvěd')),
(2004, (SELECT id FROM players WHERE name = 'Ronaldinho')),
(2005, (SELECT id FROM players WHERE name = 'Ronaldinho')),
(2006, (SELECT id FROM players WHERE name = 'Fabio Cannavaro')),
(2007, (SELECT id FROM players WHERE name = 'Kaká')),
(2008, (SELECT id FROM players WHERE name = 'Cristiano Ronaldo')),
(2009, (SELECT id FROM players WHERE name = 'Lionel Messi')),
(2010, (SELECT id FROM players WHERE name = 'Lionel Messi')),
(2011, (SELECT id FROM players WHERE name = 'Lionel Messi')),
(2012, (SELECT id FROM players WHERE name = 'Lionel Messi')),
(2013, (SELECT id FROM players WHERE name = 'Cristiano Ronaldo')),
(2014, (SELECT id FROM players WHERE name = 'Cristiano Ronaldo')),
(2015, (SELECT id FROM players WHERE name = 'Lionel Messi')),
(2016, (SELECT id FROM players WHERE name = 'Cristiano Ronaldo')),
(2017, (SELECT id FROM players WHERE name = 'Cristiano Ronaldo')),
(2018, (SELECT id FROM players WHERE name = 'Luka Modrić')),
(2019, (SELECT id FROM players WHERE name = 'Lionel Messi')),
(2021, (SELECT id FROM players WHERE name = 'Lionel Messi')),
(2022, (SELECT id FROM players WHERE name = 'Karim Benzema')),
(2023, (SELECT id FROM players WHERE name = 'Lionel Messi')),
(2024, (SELECT id FROM players WHERE name = 'Rodri')),
(2025, (SELECT id FROM players WHERE name = 'Ousmane Dembélé'));

-- Seed Nominations for 2025
INSERT INTO nominations (ceremony_id, player_id, rank, votes_received) VALUES
((SELECT id FROM ceremonies WHERE year = 2025), (SELECT id FROM players WHERE name = 'Ousmane Dembélé'), 1, 100),
((SELECT id FROM ceremonies WHERE year = 2025), (SELECT id FROM players WHERE name = 'Lamine Yamal'), 2, 90),
((SELECT id FROM ceremonies WHERE year = 2025), (SELECT id FROM players WHERE name = 'Vitinha'), 3, 85),
((SELECT id FROM ceremonies WHERE year = 2025), (SELECT id FROM players WHERE name = 'Mohamed Salah'), 4, 80),
((SELECT id FROM ceremonies WHERE year = 2025), (SELECT id FROM players WHERE name = 'Raphinha'), 5, 75),
((SELECT id FROM ceremonies WHERE year = 2025), (SELECT id FROM players WHERE name = 'Achraf Hakimi'), 6, 70),
((SELECT id FROM ceremonies WHERE year = 2025), (SELECT id FROM players WHERE name = 'Kylian Mbappé'), 7, 65),
((SELECT id FROM ceremonies WHERE year = 2025), (SELECT id FROM players WHERE name = 'Cole Palmer'), 8, 60),
((SELECT id FROM ceremonies WHERE year = 2025), (SELECT id FROM players WHERE name = 'Gianluigi Donnarumma'), 9, 55),
((SELECT id FROM ceremonies WHERE year = 2025), (SELECT id FROM players WHERE name = 'Nuno Mendes'), 10, 50);

-- Example nominations for other years (Simplified for brevity but including winners at rank 1)
-- In a real scenario, we'd add all 10 for each year.
INSERT INTO nominations (ceremony_id, player_id, rank, votes_received) VALUES
((SELECT id FROM ceremonies WHERE year = 1998), (SELECT id FROM players WHERE name = 'Zinedine Zidane'), 1, 244),
((SELECT id FROM ceremonies WHERE year = 1998), (SELECT id FROM players WHERE name = 'Davor Šuker'), 2, 68),
((SELECT id FROM ceremonies WHERE year = 1999), (SELECT id FROM players WHERE name = 'Rivaldo'), 1, 219),
((SELECT id FROM ceremonies WHERE year = 1999), (SELECT id FROM players WHERE name = 'David Beckham'), 2, 154),
((SELECT id FROM ceremonies WHERE year = 2000), (SELECT id FROM players WHERE name = 'Luis Figo'), 1, 197),
((SELECT id FROM ceremonies WHERE year = 2000), (SELECT id FROM players WHERE name = 'Zinedine Zidane'), 2, 181),
((SELECT id FROM ceremonies WHERE year = 2024), (SELECT id FROM players WHERE name = 'Rodri'), 1, 1170),
((SELECT id FROM ceremonies WHERE year = 2024), (SELECT id FROM players WHERE name = 'Vinícius Júnior'), 2, 1129),
((SELECT id FROM ceremonies WHERE year = 2023), (SELECT id FROM players WHERE name = 'Lionel Messi'), 1, 462),
((SELECT id FROM ceremonies WHERE year = 2023), (SELECT id FROM players WHERE name = 'Erling Haaland'), 2, 357);
